-- Application database schema
-- Requires: postgres started with wal_level=logical (set in docker-compose command args)

-- ── accounts: SCD1 dimension (trading account holder) ────────────────────────
CREATE TABLE IF NOT EXISTS accounts (
    account_id BIGINT       PRIMARY KEY,
    name       TEXT         NOT NULL,
    country    TEXT         NOT NULL DEFAULT 'GB',
    tier       TEXT         NOT NULL DEFAULT 'retail',   -- retail / premier / business / wealth
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- REPLICA IDENTITY FULL so Debezium captures before-images on UPDATE (needed for SCD1
-- dedup + dimension-change handling downstream).
ALTER TABLE accounts REPLICA IDENTITY FULL;

-- ── trades: append-only fills (immutable executions) ─────────────────────────
-- Each row is one execution. Positions are DERIVED downstream by folding signed
-- fills per (account_id, symbol). No updates/deletes → append-only.
CREATE TABLE IF NOT EXISTS trades (
    trade_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  BIGINT        NOT NULL,
    symbol      TEXT          NOT NULL,
    side        TEXT          NOT NULL,            -- BUY / SELL
    quantity    INTEGER       NOT NULL,
    price       NUMERIC(12,4) NOT NULL,
    executed_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);
-- Insert-only: default replica identity is enough (Debezium needs only 'after').

-- Per-table publications so each Debezium slot streams only its own table's WAL —
-- trades is high-volume; don't make the accounts slot process it.
CREATE PUBLICATION dbz_pub_accounts FOR TABLE accounts;
CREATE PUBLICATION dbz_pub_trades   FOR TABLE trades;
